=== Shaganashree97/iwp-lab/xml xsd/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.javatpoint.com"
xmlns="http://www.javatpoint.com"
elementFormDefault="qualified">
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firstname" type="xs:string"/>
              <xs:element name="lastname" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Shaganashree97/iwp-lab/xml xsd/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns="http://www.javatpoint.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.javatpoint.com employee.xsd">

  <employee id="001">
    <firstname>Shagana</firstname>
    <lastname>P L</lastname>
    <email>shag@google.com</email>
  </employee>
  <employee id="002">
    <firstname>Shree</firstname>
    <lastname>P L</lastname>
    <email>sh@google.com</email>
  </employee>

</employees>
